lib/werkzeug/urls.py
       This changed in 0.5 where only "&" is supported.  If you want to
       use ";" instead a different `separator` can be provided.

       The `cls` parameter was added.

    :param s: a string with the query string to decode.
    :param charset: the charset of the query string.
    :param decode_keys: set to `True` if you want the keys to be decoded
                        as well.
    :param include_empty: Set to `False` if you don't want empty values to
                          appear in the dict.
    :param errors: the decoding error behavior.
    :param separator: the pair separator to be used, defaults to ``&``
    :param cls: an optional dict class to use.  If this is not specified
                       or `None` the default :class:`MultiDict` is used.
    """
    if cls is None:
        cls = MultiDict
    return cls(_url_decode_impl(str(s).split(separator), charset, decode_keys,
                                include_empty, errors))


def url_decode_stream(stream, charset='utf-8', decode_keys=False,
                      include_empty=True, errors='replace', separator='&',
                      cls=None, limit=None, return_iterator=False):
    """Works like :func:`url_decode` but decodes a stream.  The behavior
    of stream and limit follows functions like
    :func:`~werkzeug.wsgi.make_line_iter`.  The generator of pairs is
    directly fed to the `cls` so you can consume the data while it's
    parsed.

    .. versionadded:: 0.8

    :param stream: a stream with the encoded querystring
    :param charset: the charset of the query string.
    :param decode_keys: set to `True` if you want the keys to be decoded
                        as well.
    :param include_empty: Set to `False` if you don't want empty values to
                          appear in the dict.
    :param errors: the decoding error behavior.
    :param separator: the pair separator to be used, defaults to ``&``
    :param cls: an optional dict class to use.  If this is not specified
                       or `None` the default :class:`MultiDict` is used.
    :param limit: the content length of the URL data.  Not necessary if
                  a limited stream is provided.
    :param return_iterator: if set to `True` the `cls` argument is ignored
                            and an iterator over all decoded pairs is
                            returned
    """
    if return_iterator:
        cls = lambda x: x
    elif cls is None:
        cls = MultiDict
    pair_iter = make_chunk_iter(stream, separator, limit)
    return cls(_url_decode_impl(pair_iter, charset, decode_keys,
                                include_empty, errors))


def _url_decode_impl(pair_iter, charset, decode_keys, include_empty,
                     errors):
    for pair in pair_iter:
        if not pair:
            continue
        if '=' in pair:
            key, value = pair.split('=', 1)
        else:
            if not include_empty:
                continue
            key = pair
            value = ''
        key = _unquote_plus(key)
        if decode_keys:
            key = _decode_unicode(key, charset, errors)
        yield key, url_unquote_plus(value, charset, errors)


def url_encode(obj, charset='utf-8', encode_keys=False, sort=False, key=None,
               separator='&'):
    """URL encode a dict/`MultiDict`.  If a value is `None` it will not appear
    in the result string.  Per default only values are encoded into the target
    charset strings.  If `encode_keys` is set to ``True`` unicode keys are
    supported too.

    If `sort` is set to `True` the items are sorted by `key` or the default
    sorting algorithm.

    .. versionadded:: 0.5
        `sort`, `key`, and `separator` were added.

    :param obj: the object to encode into a query string.
    :param charset: the charset of the query string.
    :param encode_keys: set to `True` if you have unicode keys.
    :param sort: set to `True` if you want parameters to be sorted by `key`.
    :param separator: the separator to be used for the pairs.
    :param key: an optional function to be used for sorting.  For more details
                check out the :func:`sorted` documentation.
    """
    return separator.join(_url_encode_impl(obj, charset, encode_keys, sort, key))


def url_encode_stream(obj, stream=None, charset='utf-8', encode_keys=False,
                      sort=False, key=None, separator='&'):
    """Like :meth:`url_encode` but writes the results to a stream
    object.  If the stream is `None` a generator over all encoded
    pairs is returned.

    .. versionadded:: 0.8

    :param obj: the object to encode into a query string.
    :param stream: a stream to write the encoded object into or `None` if
                   an iterator over the encoded pairs should be returned.  In
                   that case the separator argument is ignored.
    :param charset: the charset of the query string.
    :param encode_keys: set to `True` if you have unicode keys.
    :param sort: set to `True` if you want parameters to be sorted by `key`.
    :param separator: the separator to be used for the pairs.
    :param key: an optional function to be used for sorting.  For more details
                check out the :func:`sorted` documentation.
    """
    gen = _url_encode_impl(obj, charset, encode_keys, sort, key)
    if stream is None:
        return gen
    for idx, chunk in enumerate(gen):
        if idx:
            stream.write(separator)
        stream.write(chunk)


def _url_encode_impl(obj, charset, encode_keys, sort, key):
    iterable = iter_multi_items(obj)
    if sort:
        iterable = sorted(iterable, key=key)
    for key, value in iterable:
        if value is None:
            continue
        if encode_keys and isinstance(key, unicode):
            key = key.encode(charset)
        else:
            key = str(key)
        if isinstance(value, unicode):
            value = value.encode(charset)
        else:
            value = str(value)
        yield '%s=%s' % (_quote(key), _quote_plus(value))


def url_quote(s, charset='utf-8', safe='/:'):
    """URL encode a single string with a given encoding.

    :param s: the string to quote.
    :param charset: the charset to be used.
    :param safe: an optional sequence of safe characters.
    """
    if isinstance(s, unicode):
        s = s.encode(charset)
    elif not isinstance(s, str):
        s = str(s)
    return _quote(s, safe=safe)


def url_quote_plus(s, charset='utf-8', safe=''):
    """URL encode a single string with the given encoding and convert
    whitespace to "+".

    :param s: the string to quote.
    :param charset: the charset to be used.
    :param safe: an optional sequence of safe characters.
    """
    if isinstance(s, unicode):
        s = s.encode(charset)
    elif not isinstance(s, str):
        s = str(s)
    return _quote_plus(s, safe=safe)


def url_unquote(s, charset='utf-8', errors='replace'):
    """URL decode a single string with a given decoding.

    Per default encoding errors are ignored.  If you want a different behavior
    you can set `errors` to ``'replace'`` or ``'strict'``.  In strict mode a
    `HTTPUnicodeError` is raised.

    :param s: the string to unquote.
    :param charset: the charset to be used.
    :param errors: the error handling for the charset decoding.
    """
    if isinstance(s, unicode):
        s = s.encode(charset)
    return _decode_unicode(_unquote(s), charset, errors)


def url_unquote_plus(s, charset='utf-8', errors='replace'):
    """URL decode a single string with the given decoding and decode
    a "+" to whitespace.

    Per default encoding errors are ignored.  If you want a different behavior
    you can set `errors` to ``'replace'`` or ``'strict'``.  In strict mode a
    `HTTPUnicodeError` is raised.

    :param s: the string to unquote.
    :param charset: the charset to be used.
    :param errors: the error handling for the charset decoding.
    """
    if isinstance(s, unicode):
        s = s.encode(charset)
    return _decode_unicode(_unquote_plus(s), charset, errors)


def url_fix(s, charset='utf-8'):
    r"""Sometimes you get an URL by a user that just isn't a real URL because
    it contains unsafe characters like ' ' and so on.  This function can fix
    some of the problems in a similar way browsers handle data entered by the
    user:

    >>> url_fix(u'http://de.wikipedia.org/wiki/Elf (Begriffskl\xe4rung)')
    'http://de.wikipedia.org/wiki/Elf%20%28Begriffskl%C3%A4rung%29'

    :param s: the string with the URL to fix.
    :param charset: The target charset for the URL if the url was given as
                    unicode string.
    """
    if isinstance(s, unicode):
        s = s.encode(charset, 'replace')
    scheme, netloc, path, qs, anchor = _safe_urlsplit(s)
    path = _quote(path, '/%')
    qs = _quote_plus(qs, ':&%=')
    return urlparse.urlunsplit((scheme, netloc, path, qs, anchor))


class Href(object):
    """Implements a callable that constructs URLs with the given base. The
    function can be called with any number of positional and keyword
    arguments which than are used to assemble the URL.  Works with URLs
    and posix paths.

    Positional arguments are appended as individual segments to
    the path of the URL:

    >>> href = Href('/foo')
    >>> href('bar', 23)
    '/foo/bar/23'
    >>> href('foo', bar=23)
    '/foo/foo?bar=23'

    If any of the arguments (positional or keyword) evaluates to `None` it
    will be skipped.  If no keyword arguments are given the last argument
    can be a :class:`dict` or :class:`MultiDict` (or any other dict subclass),
    otherwise the keyword arguments are used for the query parameters, cutting
    off the first trailing underscore of the parameter name:

    >>> href(is_=42)
    '/foo?is=42'
    >>> href({'foo': 'bar'})
    '/foo?foo=bar'

    Combining of both methods is not allowed:

    >>> href({'foo': 'bar'}, bar=42)
    Traceback (most recent call last):
      ...

application/models.py
# /usr/env python
#-*- coding:utf8 -*-

from google.appengine.ext import db


class Search(db.Model):

    key_word= db.StringProperty()
    location= db.StringProperty()
    created_at = db.DateTimeProperty(auto_now_add=True)


class Tweet(db.Model):
    text = db.TextProperty()
    from_user= db.StringProperty()
    from_user_name= db.StringProperty()
    created_at = db.StringProperty()
    loation = db.StringProperty()
    image=db.StringProperty()
    weight=db.FloatProperty()
    sentiment=db.FloatProperty()

class HighHit(db.Model):
    word=db.StringProperty()
    search=db.ReferenceProperty(Search)

class HittoTweet(db.Model):
    tweet=db.ReferenceProperty(Tweet)
    highhit=db.ReferenceProperty(HighHit)

templates/index.html
{% extends 'layout.html'%}
{% block body %}
 <div class="row-fluid">

<div class="page-header">
  <h2>Search</h2>
</div>

<div>

<form action="/action/" method="post">
<label>Word: <input type="text" name="key_word" id="key_word"></label>
<br/>
<label>Location: <input type="text" name="location" id="location"></label>
</br>
<button class="btn" id="s2" type="submit">Search</button>
    </form>

<div id="result">
<div>
</div>
{% endblock body%} 
{% block script %}
<script type="text/javascript">
$("#s1").click(function() {
$.post('/action/',{'location':$("#location").val(),'key_word':$("#key_word").val()}, function(data) {
  data=$.parseJSON(data);
alert(data);
  $("#result").html(data);
});
});

</script>
{% endblock script %}

templates/layout.html
<!DOCTYPE HTML>
<html>
<head>

<title>Twitter-{% block title%}index{% endblock title%}</title>

<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="{{ url_for('static', filename='css/bootstrap.css')}}" rel="stylesheet">
</head>
<body>

{%block navbar %}
<div class="navbar">
  <div class="navbar-inner">
    <a class="brand" href="/">Twitter</a>
  </div>
</div>
{%endblock navbar%}
<div class="container well">


{% block body %}




{% endblock body%} 

</div>
<script src="{{ url_for('static', filename='js/jquery.js') }}"></script>
<script src="{{ url_for('static', filename='js/bootstrap.js') }}"></script>

{% block script %}

{% endblock script%}
{% for message in get_flashed_messages() %}
<div class=flash>{{ message }}</div>
{% endfor %}



</body>
</html>

templates/result.html
{% extends 'layout.html'%}
{% block title %}{{key_word}}{% endblock title%}
{% block body %}


<div class="offset2">

<div class="page-header" >
  <h3>{{key_word}}</h3>
</div>
<div class="span10">
{% for hit in h%}
{{hit.word}}<br>
------------------------------------------------</br>
{% for r in hit.hittotweet_set.run() %}
User:{{r.tweet.from_user}}</br>
Tweet:{{r.tweet.text}}</br>
sentiment:{% if r.tweet.sentiment >0.1 -%}Positive {% elif -0.1<r.tweet.sentiment< 0.1 %} Netural {% else %} Negative {% endif %}</br>
image:<image src="{{r.tweet.image}}"/></br>
------------</br>
{% else %}
no popular tweets under this word</br>
------------------------------------------------</br>
{% endfor %}</br>

{% endfor %}
</div>

</div>

{% endblock body %}
{% block script %}

{% endblock script %}

templates/upload.html
{% extends 'layout.html'%}
{% block title%}
Upload new video
{% endblock%}


{%block navbar %}
<div class="navbar">
  <div class="navbar-inner">
    <a class="brand" href="/">MYyoutube</a>
    <ul class="nav">
      <li><a href="/">Home</a></li>
      <li class='active'><a href="{{ url_for('upload_file')}}">Upload</a></li>
    </ul>
  </div>
</div>

{%endblock navbar%}

{% block body%}

    <h1>Upload new File</h1>
    <form class="form-inline" action="" method=post enctype=multipart/form-data>

<label>Name</label>: <input type=text name='name'>
<span class="help-block">Example block-level help text here.</span>
<label>File</label>: <input type=file name=file><br/>
<button class="btn " type="submit">Upload</button>
    </form>
{% endblock body%}

templates/video.html
{% extends 'layout.html'%}
{% block title %}{{video.name}}{% endblock title%}
{% block body %}


<div class="offset2">

<div class="page-header" >
  <h3>{{video.name}}</h3>
</div>

<div class="span4">
<video height="270" width="480" id="myVideo"  controls>
 <source src="/static/uploads/{{video.filename}}.mp4" type="video/mp4" >
</video>
</div>


<div class="span10">
<label id ="like_num">Like:{{video.rates}}</label>
<button id='like' class="btn" type="button"><i class="icon-plus"></i>Like</button>
</div>

</div>

{% endblock body %}
{% block script %}
<script type="text/javascript" src="{{ url_for('static', filename='jwplayer/jwplayer.js')}}"></script>
<script type="text/javascript">jwplayer.key="ABCDEFGHIJKLMOPQ";</script>
<script type="text/javascript">
 jwplayer("myVideo").setup({
         'file': "/static/uploads/{{video.filename}}.mp4",
         'image':"/static/uploads/{{video.filename}}.png",
        'height': 270,
        'width': 480,
	'provider': "rtmp",
        'streamer': "rtmp://sxxxxxxxxxxxx/cfx/st",
	'modes': [
        { type: 'html5' },
        { type: 'flash', src: '/jwplayer/player.swf' }
    ]
    });


$("#like").click(function() {
$.post('/like/',{'video_id':{{video.id}}}, function(data) {
  data=$.parseJSON(data);
  $('#like_num').html("Like:"+data.like);
});
});

</script>


{% endblock script %}